In [1]:
import pandas as pd 
import numpy as np

In [2]:
df = pd.read_csv(r"../../data/income.csv",names=["name","income"],skiprows=1)

        name    income
0        Rob      5000
1      Rafiq      6000
2       Nina      4000
3      Sofia      7500
4      Mohan      8000
5        Tao      7000
6  Elon Musk  10000000

             income
count  7.000000e+00
mean   1.433929e+06
std    3.777283e+06
min    4.000000e+03
25%    5.500000e+03
50%    7.000000e+03
75%    7.750000e+03
max    1.000000e+07

5500.0

6000

5000

10000000.0

In [8]:
perc_99=df['income'].quantile(0.99)

9400479.999999994

In [9]:
df[df['income']>perc_99]

        name    income
6  Elon Musk  10000000

In [10]:
new_df= df[df['income']<perc_99]

    name  income
0    Rob    5000
1  Rafiq    6000
2   Nina    4000
3  Sofia    7500
4  Mohan    8000
5    Tao    7000

In [11]:
df.replace(df['income'][3],np.NaN,inplace=True)

        name      income
0        Rob      5000.0
1      Rafiq      6000.0
2       Nina      4000.0
3      Sofia         NaN
4      Mohan      8000.0
5        Tao      7000.0
6  Elon Musk  10000000.0

1671666.6666666667

In [13]:
new_df=df.fillna(df['income'].median())

        name      income
0        Rob      5000.0
1      Rafiq      6000.0
2       Nina      4000.0
3      Sofia      6500.0
4      Mohan      8000.0
5        Tao      7000.0
6  Elon Musk  10000000.0

0        4000.0
1        5000.0
2        6000.0
3        7000.0
4        8000.0
5    10000000.0
Name: income, dtype: float64