In [1]:
import pandas as pd
india_weather={
    "city":["mumbai","dehli","banglore"],
    "temperature":[32,45,22],
    "humidity":[33,55,22]}
df1=pd.DataFrame(india_weather)
df1

       city  temperature  humidity
0    mumbai           32        33
1     dehli           45        55
2  banglore           22        22

In [2]:
us_weather={
    "city": ["new york","chicago","orlando"],
    "temperature": [21,14,35],
    "humidity": [68, 65, 75]}
df2=pd.DataFrame(us_weather)
df2

       city  temperature  humidity
0  new york           21        68
1   chicago           14        65
2   orlando           35        75

In [3]:
df=pd.concat([df1,df2],ignore_index=True)
df

       city  temperature  humidity
0    mumbai           32        33
1     dehli           45        55
2  banglore           22        22
3  new york           21        68
4   chicago           14        65
5   orlando           35        75

In [4]:
df=pd.concat([df1,df2],keys=["ind","us"])
df

           city  temperature  humidity
ind 0    mumbai           32        33
    1     dehli           45        55
    2  banglore           22        22
us  0  new york           21        68
    1   chicago           14        65
    2   orlando           35        75

In [5]:
df.loc["ind"]

       city  temperature  humidity
0    mumbai           32        33
1     dehli           45        55
2  banglore           22        22

In [6]:
df=pd.concat([df1,df2],axis=1)
df

       city  temperature  humidity      city  temperature  humidity
0    mumbai           32        33  new york           21        68
1     dehli           45        55   chicago           14        65
2  banglore           22        22   orlando           35        75

In [7]:
temp_weather={
    "city":["mumbai","dehli","banglore"],
    "temperature":[32,45,22],
    }
df3=pd.DataFrame(temp_weather,index=[0,1,2])
df3

       city  temperature
0    mumbai           32
1     dehli           45
2  banglore           22

In [8]:
temp_weather2={
    "city": ["mumbai","banglore","dehli"],
    "temperature": [21,14,35],
    }
df4=pd.DataFrame(temp_weather2,index=[0,2,1])
df4

       city  temperature
0    mumbai           21
2  banglore           14
1     dehli           35

In [9]:
df=pd.concat([df3,df4],axis=1)
df

       city  temperature      city  temperature
0    mumbai           32    mumbai           21
1     dehli           45     dehli           35
2  banglore           22  banglore           14

In [10]:
s=pd.Series(["hot","dry","rain"],name="event")
s

0     hot
1     dry
2    rain
Name: event, dtype: object

In [12]:
df=pd.concat([df3,s],axis=1)
df

       city  temperature event
0    mumbai           32   hot
1     dehli           45   dry
2  banglore           22  rain