In [1]:
import pandas as pd
df=pd.read_csv("../../data/weather_data.csv")

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow
4  1/5/2017           32          4   Rain
5  1/6/2017           31          2  Sunny

In [3]:
import openpyxl
df = pd.read_excel("C:\\Users\\ASUS\\Downloads\\weather_data.xlsx","Sheet1")

         day  temperature  windspeed  event
0 2017-01-01           32          6   Rain
1 2017-01-02           35          7  Sunny
2 2017-01-03           28          2   Snow

In [4]:
weather_data={ 'day':['1/1/2017','1/2/2017','1/3/2017'],
              'temperature':[34,43,22],
              'windspeed':[3,5,6],
              'event':['rain','sunny','snow']
             }
df=pd.DataFrame(weather_data)

        day  temperature  windspeed  event
0  1/1/2017           34          3   rain
1  1/2/2017           43          5  sunny
2  1/3/2017           22          6   snow

In [5]:
weather_data = [
    ('1/1/2017',32,6,'Rain'),
    ('1/2/2017',35,7,'Sunny'),
    ('1/3/2017',28,2,'Snow')
]
df=pd.DataFrame(weather_data,columns=['day','temp','windspeed','event'])

        day  temp  windspeed  event
0  1/1/2017    32          6   Rain
1  1/2/2017    35          7  Sunny
2  1/3/2017    28          2   Snow

In [ ]:
weather_data = [
    {'day': '1/1/2017', 'temperature': 32, 'windspeed': 6, 'event': 'Rain'},
    {'day': '1/2/2017', 'temperature': 35, 'windspeed': 7, 'event': 'Sunny'},
    {'day': '1/3/2017', 'temperature': 28, 'windspeed': 2, 'event': 'Snow'},
    
]