In [1]:
import pandas as pd
import numpy as np
df = pd.read_csv(r"../../data/weather_data.csv",parse_dates=['day'])
df.set_index('day',inplace=True)

            temperature  windspeed  event
day
2017-01-01           32          6   Rain
2017-01-02       -99999          7  Sunny
2017-01-03           28     -99999   Snow
2017-01-04       -99999          7      0
2017-01-05           32     -99999   Rain
2017-01-06           31          2  Sunny
2017-01-06           34          5      0

In [2]:
df=df.replace(-99999,value=np.NaN)

            temperature  windspeed  event
day
2017-01-01         32.0        6.0   Rain
2017-01-02          NaN        7.0  Sunny
2017-01-03         28.0        NaN   Snow
2017-01-04          NaN        7.0      0
2017-01-05         32.0        NaN   Rain
2017-01-06         31.0        2.0  Sunny
2017-01-06         34.0        5.0      0

In [3]:
new_df =df.fillna(0)

            temperature  windspeed  event
day
2017-01-01         32.0        6.0   Rain
2017-01-02          0.0        7.0  Sunny
2017-01-03         28.0        0.0   Snow
2017-01-04          0.0        7.0      0
2017-01-05         32.0        0.0   Rain
2017-01-06         31.0        2.0  Sunny
2017-01-06         34.0        5.0      0

In [4]:
new_df=df.fillna({'temperature':0,'windspeed':0,'event':"No event"})

            temperature  windspeed  event
day
2017-01-01         32.0        6.0   Rain
2017-01-02          0.0        7.0  Sunny
2017-01-03         28.0        0.0   Snow
2017-01-04          0.0        7.0      0
2017-01-05         32.0        0.0   Rain
2017-01-06         31.0        2.0  Sunny
2017-01-06         34.0        5.0      0

In [5]:
new_df=df.fillna(method='ffill')

C:\Users\ASUS\AppData\Local\Temp\ipykernel_16208\1317224737.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  new_df=df.fillna(method='ffill')

            temperature  windspeed  event
day
2017-01-01         32.0        6.0   Rain
2017-01-02         32.0        7.0  Sunny
2017-01-03         28.0        7.0   Snow
2017-01-04         28.0        7.0      0
2017-01-05         32.0        7.0   Rain
2017-01-06         31.0        2.0  Sunny
2017-01-06         34.0        5.0      0

In [6]:
new_df=df.ffill()

            temperature  windspeed  event
day
2017-01-01         32.0        6.0   Rain
2017-01-02         32.0        7.0  Sunny
2017-01-03         28.0        7.0   Snow
2017-01-04         28.0        7.0      0
2017-01-05         32.0        7.0   Rain
2017-01-06         31.0        2.0  Sunny
2017-01-06         34.0        5.0      0

In [7]:
new_df=df.bfill(limit=1)

            temperature  windspeed  event
day
2017-01-01         32.0        6.0   Rain
2017-01-02         28.0        7.0  Sunny
2017-01-03         28.0        7.0   Snow
2017-01-04         32.0        7.0      0
2017-01-05         32.0        2.0   Rain
2017-01-06         31.0        2.0  Sunny
2017-01-06         34.0        5.0      0

In [8]:
new_df=df.bfill(axis=1)

           temperature windspeed  event
day
2017-01-01        32.0       6.0   Rain
2017-01-02         7.0       7.0  Sunny
2017-01-03        28.0      Snow   Snow
2017-01-04         7.0       7.0      0
2017-01-05        32.0      Rain   Rain
2017-01-06        31.0       2.0  Sunny
2017-01-06        34.0       5.0      0

In [9]:
new_df=df.interpolate()

C:\Users\ASUS\AppData\Local\Temp\ipykernel_16208\1725489846.py:1: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  new_df=df.interpolate()

            temperature  windspeed  event
day
2017-01-01         32.0        6.0   Rain
2017-01-02         30.0        7.0  Sunny
2017-01-03         28.0        7.0   Snow
2017-01-04         30.0        7.0      0
2017-01-05         32.0        4.5   Rain
2017-01-06         31.0        2.0  Sunny
2017-01-06         34.0        5.0      0

In [10]:

new_df=df.infer_objects(copy=False).interpolate(method="time")

C:\Users\ASUS\AppData\Local\Temp\ipykernel_16208\434984852.py:1: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  new_df=df.infer_objects(copy=False).interpolate(method="time")

            temperature  windspeed  event
day
2017-01-01         32.0        6.0   Rain
2017-01-02         30.0        7.0  Sunny
2017-01-03         28.0        7.0   Snow
2017-01-04         30.0        7.0      0
2017-01-05         32.0        4.5   Rain
2017-01-06         31.0        2.0  Sunny
2017-01-06         34.0        5.0      0

In [11]:
new_df = df.infer_objects(copy=False)
new_df = df.interpolate(method="time")

C:\Users\ASUS\AppData\Local\Temp\ipykernel_16208\3141399713.py:2: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  new_df = df.interpolate(method="time")

            temperature  windspeed  event
day
2017-01-01         32.0        6.0   Rain
2017-01-02         30.0        7.0  Sunny
2017-01-03         28.0        7.0   Snow
2017-01-04         30.0        7.0      0
2017-01-05         32.0        4.5   Rain
2017-01-06         31.0        2.0  Sunny
2017-01-06         34.0        5.0      0

In [12]:
new_df=df.dropna()

            temperature  windspeed  event
day
2017-01-01         32.0        6.0   Rain
2017-01-06         31.0        2.0  Sunny
2017-01-06         34.0        5.0      0

In [13]:
new_df=df.dropna(how="all")

            temperature  windspeed  event
day
2017-01-01         32.0        6.0   Rain
2017-01-02          NaN        7.0  Sunny
2017-01-03         28.0        NaN   Snow
2017-01-04          NaN        7.0      0
2017-01-05         32.0        NaN   Rain
2017-01-06         31.0        2.0  Sunny
2017-01-06         34.0        5.0      0

In [14]:
new_df=df.dropna(thresh=2)

            temperature  windspeed  event
day
2017-01-01         32.0        6.0   Rain
2017-01-02          NaN        7.0  Sunny
2017-01-03         28.0        NaN   Snow
2017-01-04          NaN        7.0      0
2017-01-05         32.0        NaN   Rain
2017-01-06         31.0        2.0  Sunny
2017-01-06         34.0        5.0      0

In [15]:
dt = pd.date_range("01-01-2017","01-11-2017")
idx = pd.DatetimeIndex(dt)
df = df.reindex(idx)

ValueError: cannot reindex on an axis with duplicate labels