In [1]:
import pandas as pd
df1 = pd.DataFrame({
    "city": ["new york","chicago","orlando"],
    "temperature": [21,14,35],
})
df1

       city  temperature
0  new york           21
1   chicago           14
2   orlando           35

In [2]:
df2 = pd.DataFrame({
    "city": ["chicago","new york","orlando"],
    "humidity": [65,68,75],
})
df2

       city  humidity
0   chicago        65
1  new york        68
2   orlando        75

In [3]:
df = pd.merge(df1,df2,on="city")
df

       city  temperature  humidity
0  new york           21        68
1   chicago           14        65
2   orlando           35        75

In [4]:
df1.join(df2,lsuffix="_l",rsuffix="_r")

     city_l  temperature    city_r  humidity
0  new york           21   chicago        65
1   chicago           14  new york        68
2   orlando           35   orlando        75

In [5]:
df1 = pd.DataFrame({
    "city": ["new york","chicago","orlando", "baltimore"],
    "temperature": [21,14,35, 38],
})
df1

        city  temperature
0   new york           21
1    chicago           14
2    orlando           35
3  baltimore           38

In [6]:
df2 = pd.DataFrame({
    "city": ["chicago","new york","san diego"],
    "humidity": [65,68,71],
})
df2

        city  humidity
0    chicago        65
1   new york        68
2  san diego        71

In [7]:
df=pd.merge(df1,df2,on="city")
df

       city  temperature  humidity
0  new york           21        68
1   chicago           14        65

In [8]:
df=pd.merge(df1,df2,on="city",how="outer")
df

        city  temperature  humidity
0   new york         21.0      68.0
1    chicago         14.0      65.0
2    orlando         35.0       NaN
3  baltimore         38.0       NaN
4  san diego          NaN      71.0

In [9]:
df=pd.merge(df1,df2,on="city",how="left")
df

        city  temperature  humidity
0   new york           21      68.0
1    chicago           14      65.0
2    orlando           35       NaN
3  baltimore           38       NaN

In [10]:
df=pd.merge(df1,df2,on="city",how="right")
df

        city  temperature  humidity
0    chicago         14.0        65
1   new york         21.0        68
2  san diego          NaN        71

In [11]:
df=pd.merge(df1,df2,on="city",how="outer",indicator=True)
df

        city  temperature  humidity      _merge
0   new york         21.0      68.0        both
1    chicago         14.0      65.0        both
2    orlando         35.0       NaN   left_only
3  baltimore         38.0       NaN   left_only
4  san diego          NaN      71.0  right_only

In [12]:
df1 = pd.DataFrame({
    "city": ["new york","chicago","orlando", "baltimore"],
    "temperature": [21,14,35,38],
    "humidity": [65,68,71, 75]
})
df1

        city  temperature  humidity
0   new york           21        65
1    chicago           14        68
2    orlando           35        71
3  baltimore           38        75

In [13]:
df2 = pd.DataFrame({
    "city": ["chicago","new york","san diego"],
    "temperature": [21,14,35],
    "humidity": [65,68,71]
})
df2

        city  temperature  humidity
0    chicago           21        65
1   new york           14        68
2  san diego           35        71

In [14]:
df=pd.merge(df1,df2,on="city",how="outer",suffixes=("-first","-second"))
df

,city,temperature-first,humidity-first,temperature-second,humidity-second
0,new york,21.0,65.0,14.0,68.0
1,chicago,14.0,68.0,21.0,65.0
2,orlando,35.0,71.0,NaN,NaN
3,baltimore,38.0,75.0,NaN,NaN
4,san diego,NaN,NaN,35.0,71.0

In [16]:
df=pd.merge(df1,df2,on="city",how="outer",suffixes=("-uno","-duno"))
df

        city  temperature-uno  humidity-uno  temperature-duno  humidity-duno
0   new york             21.0          65.0              14.0           68.0
1    chicago             14.0          68.0              21.0           65.0
2    orlando             35.0          71.0               NaN            NaN
3  baltimore             38.0          75.0               NaN            NaN
4  san diego              NaN           NaN              35.0           71.0