In [2]:
import pandas as pd
import numpy as np
df = pd.read_csv(r"../../data/weather.csv")

       date      city  temperature  humidity
0  5/1/2017  new york           65        56
1  5/2/2017  new york           66        58
2  5/3/2017  new york           68        60
3  5/1/2017    mumbai           75        80
4  5/2/2017    mumbai           78        83
5  5/3/2017    mumbai           82        85
6  5/1/2017   beijing           80        26
7  5/2/2017   beijing           77        30
8  5/3/2017   beijing           79        35

In [4]:
df.pivot(index="city",columns="date")

         temperature                   humidity
date        5/1/2017 5/2/2017 5/3/2017 5/1/2017 5/2/2017 5/3/2017
city
beijing           80       77       79       26       30       35
mumbai            75       78       82       80       83       85
new york          65       66       68       56       58       60

date      5/1/2017  5/2/2017  5/3/2017
city
beijing         80        77        79
mumbai          75        78        82
new york        65        66        68

In [7]:
df = pd.read_csv(r"../../data/weather2.csv")

       date      city  temperature  humidity
0  5/1/2017  new york           65        56
1  5/1/2017  new york           61        54
2  5/2/2017  new york           70        60
3  5/2/2017  new york           72        62
4  5/1/2017    mumbai           75        80
5  5/1/2017    mumbai           78        83
6  5/2/2017    mumbai           82        85
7  5/2/2017    mumbai           80        26

         humidity          temperature
date     5/1/2017 5/2/2017    5/1/2017 5/2/2017
city
mumbai       81.5     55.5        76.5     81.0
new york     55.0     61.0        63.0     71.0

         humidity          temperature
date     5/1/2017 5/2/2017    5/1/2017 5/2/2017
city
mumbai        163      111         153      162
new york      110      122         126      142

         humidity              temperature
date     5/1/2017 5/2/2017 All    5/1/2017 5/2/2017 All
city
mumbai         80       26  26          75       80  75
new york       54       60  54          61       70  61
All            54       26  26          61       70  61

In [13]:
df = pd.read_csv(r"../../data/weather3.csv")

        date      city  temperature  humidity
0   5/1/2017  new york           65        56
1   5/2/2017  new york           61        54
2   5/3/2017  new york           70        60
3  12/1/2017  new york           30        50
4  12/2/2017  new york           28        52
5  12/3/2017  new york           25        51

          humidity temperature
city      new york    new york
date
12/1/2017     50.0        30.0
12/2/2017     52.0        28.0
12/3/2017     51.0        25.0
5/1/2017      56.0        65.0
5/2/2017      54.0        61.0
5/3/2017      60.0        70.0

pandas._libs.tslibs.timestamps.Timestamp

             humidity temperature
city         new york    new york
date
2017-05-31  56.666667   65.333333
2017-12-31  51.000000   27.666667