In [2]:
import pandas as pd
df = pd.read_csv(r"../../data/stock_data.csv")

  tickers            eps  revenue price         people
0   GOOGL          27.82       87   845     larry page
1     WMT           4.61      484    65           n.a.
2    MSFT             -1       85    64     bill gates
3    RIL   not available       50  1023  mukesh ambani
4    TATA            5.6       -1  n.a.     ratan tata

In [2]:
df = pd.read_csv(r"../../data/stock_data.csv",skiprows=2)

    WMT           4.61  484    65           n.a.
0  MSFT             -1   85    64     bill gates
1  RIL   not available   50  1023  mukesh ambani
2  TATA            5.6   -1  n.a.     ratan tata

In [3]:
df=pd.read_csv(r"../../data/stock_data.csv",header=1)

  GOOGL          27.82   87   845     larry page
0   WMT           4.61  484    65           n.a.
1  MSFT             -1   85    64     bill gates
2  RIL   not available   50  1023  mukesh ambani
3  TATA            5.6   -1  n.a.     ratan tata

In [3]:
df = pd.read_csv(r"../../data/stock_data.csv",header=2)

    WMT           4.61  484    65           n.a.
0  MSFT             -1   85    64     bill gates
1  RIL   not available   50  1023  mukesh ambani
2  TATA            5.6   -1  n.a.     ratan tata

In [6]:
df = pd.read_csv(r"../../data/stock_data.csv",header=None,names=['ticket','esp','revenue','interest'])

                ticket      esp revenue       interest
tickers            eps  revenue   price         people
GOOGL            27.82       87     845     larry page
WMT               4.61      484      65           n.a.
MSFT                -1       85      64     bill gates
RIL      not available       50    1023  mukesh ambani
TATA               5.6       -1    n.a.     ratan tata

In [7]:
df = pd.read_csv(r"../../data/stock_data.csv",nrows=2)

  tickers    eps  revenue  price      people
0   GOOGL  27.82       87    845  larry page
1     WMT   4.61      484     65        n.a.

In [8]:
df = pd.read_csv(r"../../data/stock_data.csv",na_values=['n.a.','not available'])

  tickers    eps  revenue   price         people
0   GOOGL  27.82       87   845.0     larry page
1     WMT   4.61      484    65.0            NaN
2    MSFT  -1.00       85    64.0     bill gates
3    RIL     NaN       50  1023.0  mukesh ambani
4    TATA   5.60       -1     NaN     ratan tata

In [11]:
df = pd.read_csv(r"../../data/stock_data.csv",na_values={
    'eps':['-1'],
    'revenue':['-1'],
    'people':['n.a.','not available']
})

  tickers            eps  revenue price         people
0   GOOGL          27.82     87.0   845     larry page
1     WMT           4.61    484.0    65            NaN
2    MSFT            NaN     85.0    64     bill gates
3    RIL   not available     50.0  1023  mukesh ambani
4    TATA            5.6      NaN  n.a.     ratan tata

In [14]:
df.to_csv(r"../../data/new.csv",index=False)

Index(['tickers', 'eps', 'revenue', 'price', 'people'], dtype='object')

In [19]:
df = pd.read_excel(r"C:\Users\ASUS\Downloads\stock_data.xlsx")

  tickers            eps  revenue price         people
0   GOOGL          27.82       87   845     larry page
1     WMT           4.61      484    65           n.a.
2    MSFT             -1       85    64     bill gates
3    RIL   not available       50  1023  mukesh ambani
4    TATA            5.6       -1  n.a.     ratan tata

In [23]:
df = pd.read_excel(r"C:\Users\ASUS\Downloads\stock_data.xlsx",na_values={
    'eps':['-1'],
    'revenue':['-1'],
    'people':['n.a.','not available'],
    'price':['n.a.']
})

  tickers            eps  revenue   price         people
0   GOOGL          27.82       87   845.0     larry page
1     WMT           4.61      484    65.0            NaN
2    MSFT            NaN       85    64.0     bill gates
3    RIL   not available       50  1023.0  mukesh ambani
4    TATA            5.6       -1     NaN     ratan tata

In [26]:
def convert_people_cell(cell):
    if cell=="n.a.":
        return 'sam walton'
    return cell
def convert_price_cell(cell):
    if cell=="n.a.":
        return '50'
    return cell
df=pd.read_excel("C://Users//ASUS//Downloads//stock_data.xlsx","Sheet1",converters={
    'people':convert_people_cell,
    'price':convert_price_cell})

  tickers            eps  revenue price         people
0   GOOGL          27.82       87   845     larry page
1     WMT           4.61      484    65     sam walton
2    MSFT             -1       85    64     bill gates
3    RIL   not available       50  1023  mukesh ambani
4    TATA            5.6       -1    50     ratan tata

In [29]:
df_stocks = pd.DataFrame({
    'tickers': ['GOOGL', 'WMT', 'MSFT'],
    'price': [845, 65, 64 ],
    'pe': [30.37, 14.26, 30.97],
    'eps': [27.82, 4.61, 2.12]
})

df_weather =  pd.DataFrame({
    'day': ['1/1/2017','1/2/2017','1/3/2017'],
    'temperature': [32,35,28],
    'event': ['Rain', 'Sunny', 'Snow']

In [31]:
with pd.ExcelWriter("C://Users//ASUS//Downloads//ss.xlsx")as writer:
    df_stocks.to_excel(writer,sheet_name="stock")