In [1]:
import pandas as pd
import numpy as np
df = pd.read_csv("../../data/weather_data.csv")

          day  temperature  windspeed  event
0  01-01-2017           32          6   Rain
1  01-02-2017       -99999          7  Sunny
2  01-03-2017           28     -99999   Snow
3  01-04-2017       -99999          7      0
4  01-05-2017           32     -99999   Rain
5  01-06-2017           31          2  Sunny
6  01-06-2017           34          5      0

In [2]:
new_df=df.replace(-99999,value=np.NaN)
new_df

          day  temperature  windspeed  event
0  01-01-2017         32.0        6.0   Rain
1  01-02-2017          NaN        7.0  Sunny
2  01-03-2017         28.0        NaN   Snow
3  01-04-2017          NaN        7.0      0
4  01-05-2017         32.0        NaN   Rain
5  01-06-2017         31.0        2.0  Sunny
6  01-06-2017         34.0        5.0      0

In [3]:
new_df=df.replace(-99999,0)

          day  temperature  windspeed  event
0  01-01-2017           32          6   Rain
1  01-02-2017            0          7  Sunny
2  01-03-2017           28          0   Snow
3  01-04-2017            0          7      0
4  01-05-2017           32          0   Rain
5  01-06-2017           31          2  Sunny
6  01-06-2017           34          5      0

In [4]:
new_df=df.replace([-99999,-88888],0)

          day  temperature  windspeed  event
0  01-01-2017           32          6   Rain
1  01-02-2017            0          7  Sunny
2  01-03-2017           28          0   Snow
3  01-04-2017            0          7      0
4  01-05-2017           32          0   Rain
5  01-06-2017           31          2  Sunny
6  01-06-2017           34          5      0

In [5]:
new_df=df.replace({'temperature':-99999,'windspeed':-99999},0)

          day  temperature  windspeed  event
0  01-01-2017           32          6   Rain
1  01-02-2017            0          7  Sunny
2  01-03-2017           28          0   Snow
3  01-04-2017            0          7      0
4  01-05-2017           32          0   Rain
5  01-06-2017           31          2  Sunny
6  01-06-2017           34          5      0

In [6]:
new_df=df.replace({-99999:0,"0":"Rain"})

          day  temperature  windspeed  event
0  01-01-2017           32          6   Rain
1  01-02-2017            0          7  Sunny
2  01-03-2017           28          0   Snow
3  01-04-2017            0          7   Rain
4  01-05-2017           32          0   Rain
5  01-06-2017           31          2  Sunny
6  01-06-2017           34          5   Rain

In [7]:
new_df=df.replace({'temperature':'[A-Za-z]','windspeed':'[a-z]'},'',regex=True)

          day  temperature  windspeed  event
0  01-01-2017           32          6   Rain
1  01-02-2017       -99999          7  Sunny
2  01-03-2017           28     -99999   Snow
3  01-04-2017       -99999          7      0
4  01-05-2017           32     -99999   Rain
5  01-06-2017           31          2  Sunny
6  01-06-2017           34          5      0

In [8]:
df = pd.DataFrame({
    'score': ['exceptional','average', 'good', 'poor', 'average', 'exceptional'],
    'student': ['rob', 'maya', 'parthiv', 'tom', 'julian', 'erica']
})

         score  student
0  exceptional      rob
1      average     maya
2         good  parthiv
3         poor      tom
4      average   julian
5  exceptional    erica

In [9]:
new_df=df.replace(['poor','average','good','exceptional'],[1,2,3,4])

   score  student
0      4      rob
1      2     maya
2      3  parthiv
3      1      tom
4      2   julian
5      4    erica